### ISSUE TITLE
Awesome Project.

### ISSUE THREAD

**Issue by ghost** [bubstance/templeos-plus#1]
Just discovered this project, and I'm amazed to see that it has only 2 stars. I like that you've created scripts and a fairly detailed README. Prior to discovering this project last night, I was working on my own TempleOS Auto Installer for QEMU on Windows. Unfortunately QEMU on Windows isn't the greatest, so if you know more about this topic, I'd love to know more.

Also, I run a [website ](https://templeos.me) dedicated to documenting TempleOS, with your permission of course, I'd like to display this repo there, would that be okay?

**Comment by bubstance** [comment]
Hey there, glad you like this little project!

I have no problems at all with you linking to the repo in whatever way you would like wherever you would like; all of the files and code contained within are fully Unlicensed and public domain works with no restrictions or constraints whatsoever.

As for QEMU on Windows, my only real suggestion would be to try running QEMU under WSL2 if you haven't already; I've heard that the graphical side of WSL2 has gotten much better. Other than that, unfortunately I have nothing to really offer as I don't use Windows these days.

You may want to reach out to Jeff Irwin (@JeffIrwin) on getting TempleOS running under QEMU on Windows; as far as I know that's what he has been doing.

**Comment by JeffIrwin** [comment]
Yep, the "TempleOS basics" section on my readme linked below should still work hopefully.  A couple caveats: I don't think I ever got TempleOS audio working on Windows, and there are constant issues with the screen aspect ratio depending on how you maximize the QEMU window 

https://github.com/JeffIrwin/temple-viewer
